version: '3.8'

services:
  app:
    image: tm-serve:latest
    container_name: bzhou_ubuntu
    ports:
      - "1234:1234"
      - "8000:8000"
    privileged: true
    volumes:
      - ./startup.sh:/startup.sh
    environment:
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: /startup.sh
    tty: true
    stdin_open: true
    restart: unless-stopped

networks:
  default:
    driver: bridge